### ISSUE TITLE
Update embedded version of basetool to use Tool Labs CDN

### ISSUE THREAD

**Issue by bd808** [Krinkle/mw-tool-snapshots#13]
The version of basetool imported as a submodule predates https://github.com/Krinkle/toollabs-base/commit/a32e91c3d0c5bf41bd47e08c2503cc3f8fe4958d and thus css and javascript resources are loaded from external CDNs.

**Comment by Krinkle** [comment]
Thanks @bd808. Will need a conversion similar to https://github.com/Krinkle/mw-tool-orphantalk/commit/63c652a1e555d0798daa36c153db1b47a0cc34f0.
