### ISSUE TITLE
REL1_29 missing and master snapshot is outdated

### ISSUE THREAD

**Issue by mainframe98** [Krinkle/mw-tool-snapshots#14]
The last created snapshot of the master branch of MediaWiki was created 3212 hours ago when writing this: Tue, 28 Mar 2017 23:32:06 +0000. According to the console log, the last time the script ran was Fri, 28 Jul 2017 23:00:20 +0000 almost two weeks ago.

**Comment by Krinkle** [comment]
Looks like the git clone got corrupted. This has been fixed now.
