### ISSUE TITLE
Update log stuck

### ISSUE THREAD

**Issue by paladox** [Krinkle/mw-tool-snapshots#8]
Hi it seems every so often the update log does not update every hour please see https://tools.wmflabs.org/snapshots/#!/mediawiki-core/master which is at 165 hours since it was last updated.

**Comment by paladox** [comment]
@Krinkle

**Comment by paladox** [comment]
And also timing is out of place because when it is meant to be done for example at 7 pm it shows that it was last updated at 6 pm but by 8 pm it then shows it as 7 pm so an hour behind.

**Comment by Krinkle** [comment]
It runs every hour. However, the [git-gc](https://www.kernel.org/pub/software/scm/git/docs/git-gc.html) process in labs crashed due to the NFS maintenance last week. I've restarted it. Thanks :)

**Comment by paladox** [comment]
Oh ok thank.
