### ISSUE TITLE
wmf branch should be added back

### ISSUE THREAD

**Issue by paladox** [Krinkle/mw-tool-snapshots#9]
Hi wmf branch should be added back please.

**Comment by Krinkle** [comment]
Why? Who would want to download a tarball of a wmf branch?

**Comment by paladox** [comment]
Because it would be safer to download then alpha since it might be a tiny bit more stable then alpha.

**Comment by Krinkle** [comment]
If you need stability, use stable releases or release candidates. Using wmf branches is risky, unsupported, undocumented and does not provide any upgrade paths. They may not be compatible.
